{% set name = "libflint" %}
{% set version = "3.1.3.1" %}
{% set tar_version = ".".join(version.split(".")[:3] + "-p" + version.split(".")[3] %}
{% set build = 101 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flintlib/flint/releases/download/v{{ tar_version }}/flint-{{ tar_version }}.tar.gz
  sha256: 96637ba9de43397d06657deefe8e6dee9d226992b5526bb1c9a9d563b983e027
  patches:
    - 0001-Fix-finding-winpthreads-on-windows.patch

build:
  number: {{ build }}
  run_exports:
    - {{ pin_subpackage('libflint', max_pin='x.x') }}
  ignore_run_exports_from:
    - ntl  # ntl part is header only

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libtool                # [unix]
    - m4                     # [unix]
    - make                   # [unix]
    - cmake                  # [win]
    - ninja                  # [win]
    - pkg-config             # [win]
  host:
    - winpthreads-devel      # [win]
    - ntl                    # [not win]
    - gmp
    - mpfr

test:
  commands:
    - test -f $PREFIX/include/flint/flint.h   # [unix]
    - test -f $PREFIX/lib/libflint.so         # [linux]
    - test -f $PREFIX/lib/libflint.dylib      # [osx]
    - if not exist %LIBRARY_BIN%\flint-19.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\flint.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\flint\flint.h exit 1   # [win]

about:
  home: http://flintlib.org
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Fast Library for Number Theory

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
