{% set version = "2.6.2" %}

package:
  name: libflint
  version: {{ version }}

source:
  url: http://flintlib.org/flint-{{ version }}.tar.gz
  sha256: 5f9b45113c3b50c10564a04e9dd929eb8ad96488b5eb901db5723cd21bbae1da

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('libflint', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make              # [unix]
    - ninja             # [win]
    - cmake             # [win]
  host:
    - gmp               # [unix]
    - mpir              # [win]
    - pthreads-win32    # [win]
    - mpfr
    - ntl               # [unix]
  run:
    - gmp               # [unix]
    - mpir              # [win]
    - pthreads-win32    # [win]
    - mpfr
    - ntl               # [unix]

test:
  commands:
    - test -f $PREFIX/include/flint/flint.h   # [unix]
    - test -f $PREFIX/lib/libflint.so         # [linux]
    - test -f $PREFIX/lib/libflint.dylib      # [osx]
    - if not exist %LIBRARY_BIN%\flint-14.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\flint.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\flint\flint.h exit 1   # [win]

about:
  home: http://flintlib.org
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Fast Library for Number Theory

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
