{% set name = "libflint" %}
{% set version = "3.4.0" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flintlib/flint/releases/download/v{{ version }}/flint-{{ version }}.tar.gz
  sha256: 9497679804dead926e3affeb8d4c58739d1c7684d60c2c12827550d28e454a33

build:
  number: {{ build }}
  run_exports:
    - {{ pin_subpackage('libflint', max_pin='x.x') }}
  ignore_run_exports_from:
    - ntl  # ntl part is header only

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libtool                # [unix]
    - m4                     # [unix]
    - make                   # [unix]
    - cmake                  # [win]
    - ninja                  # [win]
    - pkg-config             # [win]
  host:
    - winpthreads-devel      # [win]
    - ntl                    # [not win]
    - gmp
    - mpfr

test:
  commands:
    - test -f $PREFIX/include/flint/flint.h   # [unix]
    - test -f $PREFIX/lib/libflint.so         # [linux]
    - test -f $PREFIX/lib/libflint.dylib      # [osx]
    - if not exist %LIBRARY_BIN%\flint-21.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\flint.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\flint\flint.h exit 1   # [win]

about:
  home: http://flintlib.org
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Fast Library for Number Theory

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
