{% set version = "2.5.2" %}

package:
  name: libflint
  version: {{ version }}

source:
  fn: flint-{{ version }}.tar.gz
  url: http://flintlib.org/flint-{{ version }}.tar.gz
  sha256: cbf1fe0034533c53c5c41761017065f85207a1b770483e98b2392315f6575e87
  patches:
    - gh-444.patch  # [win]

build:
  number: 2
  msvc_compiler: 14.0

requirements:
  build:
    - toolchain  # [unix]
    - gmp >=5.0.1,<7  # [unix]
    - mpfr 3.*
    - ntl
    - mpir 3.*  # [win]
    - cmake  # [win]
    - ninja  # [win]
  run:
    - gmp >=5.0.1,<7  # [unix]
    - mpir 3.*  # [win]
    - mpfr 3.*
    - ntl

test:
  commands:
    - test -f $PREFIX/include/flint/flint.h
    - test -f $PREFIX/lib/libflint.a
    - test -f $PREFIX/lib/libflint.so         # [linux]
    - test -f $PREFIX/lib/libflint.dylib      # [osx]

about:
  home: http://flintlib.org
  license: GPL v2+
  license_file: gpl-2.0.txt
  summary: 'Fast Library for Number Theory'

extra:
  recipe-maintainers:
    - isuruf
