{% set name = "libflint" %}
{% set version = "3.1.2" %}
{% set build = 101 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://flintlib.org/flint-{{ version }}.tar.gz
  sha256: fdb3a431a37464834acff3bdc145f4fe8d0f951dd5327c4c6f93f4cbac5c2700

build:
  number: {{ build }}
  run_exports:
    - {{ pin_subpackage('libflint', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libtool                # [unix]
    - m4                     # [unix]
    - make                   # [unix]
    - cmake                  # [win]
    - ninja                  # [win]
  host:
    - winpthreads-devel      # [win]
    - gmp
    - mpfr

test:
  commands:
    - test -f $PREFIX/include/flint/flint.h   # [unix]
    - test -f $PREFIX/lib/libflint.so         # [linux]
    - test -f $PREFIX/lib/libflint.dylib      # [osx]
    - if not exist %LIBRARY_BIN%\flint-18.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\flint.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\flint\flint.h exit 1   # [win]

about:
  home: http://flintlib.org
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Fast Library for Number Theory

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
