{% set version = "2.5.2" %}

package:
  name: libflint
  version: {{ version }}

source:
  fn: flint-{{ version }}.tar.gz
  url: http://flintlib.org/flint-{{ version }}.tar.gz
  sha256: cbf1fe0034533c53c5c41761017065f85207a1b770483e98b2392315f6575e87
  patches:
    - pie_r.diff

build:
  number: 1003
  skip: true        # [win]
  run_exports:
    - {{ pin_subpackage('libflint', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - gmp
    - mpfr
    - ntl
  run:
    - gmp
    - mpfr
    - ntl

test:
  commands:
    - test -f $PREFIX/include/flint/flint.h
    - test -f $PREFIX/lib/libflint.a
    - test -f $PREFIX/lib/libflint.so         # [linux]
    - test -f $PREFIX/lib/libflint.dylib      # [osx]

about:
  home: http://flintlib.org
  license: GPL v2+
  license_file: gpl-2.0.txt
  summary: 'Fast Library for Number Theory'

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
