{% set version = "2.7.1" %}
{% set build = 1 %}
{% if WITH_NTL is undefined %}
{% set WITH_NTL = "0" %}
{% endif %}
{% if WITH_NTL == "1" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: libflint
  version: {{ version }}

source:
  url: http://flintlib.org/flint-{{ version }}.tar.gz
  sha256: 186e2fd9ab67df8a05b122fb018269b382e4babcdb17353c4be1fe364dca481e

build:
  number: {{ build }}
  string: h{{ PKG_HASH }}_ntl_{{ build }}    # [WITH_NTL == "1"]
  string: h{{ PKG_HASH }}_nontl_{{ build }}  # [WITH_NTL == "0"]
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('libflint', max_pin='x.x') }}
  track_features:
    - flint_with_nontl  # [WITH_NTL == "0" and (linux or (osx and x86_64))]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make              # [unix]
    - ninja             # [win]
    - cmake             # [win]
  host:
    - gmp               # [unix]
    - mpir              # [win]
    - pthreads-win32    # [win]
    - mpfr
    - ntl               # [WITH_NTL=="1"]
  run:
    - gmp               # [unix]
    - mpir              # [win]
    - pthreads-win32    # [win]
    - mpfr
    - ntl               # [WITH_NTL=="1"]

test:
  commands:
    - test -f $PREFIX/include/flint/flint.h   # [unix]
    - test -f $PREFIX/lib/libflint.so         # [linux]
    - test -f $PREFIX/lib/libflint.dylib      # [osx]
    - if not exist %LIBRARY_BIN%\flint-15.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\flint.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\flint\flint.h exit 1   # [win]

about:
  home: http://flintlib.org
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Fast Library for Number Theory

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
