{% set version = "2.8.0" %}
{% set build = 0 %}
{% if WITH_NTL is undefined %}
{% set WITH_NTL = "0" %}
{% endif %}
{% if WITH_NTL == "1" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: libflint
  version: {{ version }}

source:
  url: https://flintlib.org/flint-{{ version }}.tar.gz
  sha256: 584235cdc39d779d9920eaef16fe084f3c26ffeeea003a3fff64a20a0f33449e

build:
  number: {{ build }}
  {% if WITH_NTL == "1" %}
  string: h{{ PKG_HASH }}_ntl_{{ build }}
  {% else %}
  string: h{{ PKG_HASH }}_nontl_{{ build }}
  {% endif %}
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('libflint', max_pin='x.x') }}
  {% if WITH_NTL == "0" and (linux or osx) %}
  track_features:
    - flint_with_nontl
  {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make              # [unix]
    - ninja             # [win]
    - cmake             # [win]
  host:
    - gmp               # [unix]
    - mpir              # [win]
    - pthreads-win32    # [win]
    - mpfr
  {% if WITH_NTL == "1" %}
    - ntl
  {% endif %}
  run:
    - gmp               # [unix]
    - mpir              # [win]
    - pthreads-win32    # [win]
    - mpfr
  {% if WITH_NTL == "1" %}
    - ntl
  {% endif %}

test:
  commands:
    - test -f $PREFIX/include/flint/flint.h   # [unix]
    - test -f $PREFIX/lib/libflint.so         # [linux]
    - test -f $PREFIX/lib/libflint.dylib      # [osx]
    - if not exist %LIBRARY_BIN%\flint-15.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\flint.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\flint\flint.h exit 1   # [win]

about:
  home: http://flintlib.org
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Fast Library for Number Theory

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
