{% set version = "2.6.0" %}

package:
  name: libflint
  version: {{ version }}

source:
  fn: flint-{{ version }}.tar.gz
  url: http://flintlib.org/flint-{{ version }}.tar.gz
  sha256: 9089edadd12cbbda4533ab6f58efb7565fd973b5b82a89f53f64203bc3510840
  patches:
    - pie_r.diff

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libflint', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - gmp
    - mpfr
    - ntl
  run:
    - gmp
    - mpfr
    - ntl

test:
  commands:
    - test -f $PREFIX/include/flint/flint.h
    - test -f $PREFIX/lib/libflint.a
    - test -f $PREFIX/lib/libflint.so         # [linux]
    - test -f $PREFIX/lib/libflint.dylib      # [osx]

about:
  home: http://flintlib.org
  license: GPL-2.0-or-later
  license_file: gpl-2.0.txt
  summary: Fast Library for Number Theory

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
