{% set name = "libflint" %}
{% set version = "3.0.1" %}
{% set build = 102 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://flintlib.org/flint-{{ version }}.tar.gz
  sha256: 7b311a00503a863881eb8177dbeb84322f29399f3d7d72f3b1a4c9ba1d5794b4
  patches:
    - 0001-Fix-finding-winpthreads-on-windows.patch

build:
  number: {{ build }}
  run_exports:
    - {{ pin_subpackage('libflint', max_pin='x.x') }}
  ignore_run_exports_from:
    - ntl  # ntl part is header only

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libtool                # [unix]
    - m4                     # [unix]
    - make                   # [unix]
    - cmake                  # [win]
    - ninja                  # [win]
    - pkg-config             # [win]
  host:
    - winpthreads-devel      # [win]
    - ntl                    # [not win]
    - gmp
    - mpfr

test:
  commands:
    - test -f $PREFIX/include/flint/flint.h   # [unix]
    - test -f $PREFIX/lib/libflint.so         # [linux]
    - test -f $PREFIX/lib/libflint.dylib      # [osx]
    - if not exist %LIBRARY_BIN%\flint-18.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\flint.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\flint\flint.h exit 1   # [win]

about:
  home: http://flintlib.org
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Fast Library for Number Theory

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
