{% set name = "libflint" %}
{% set version = "3.0.1" %}
{% set build = 1 %}

{% if WITH_NTL is undefined %}
{% set WITH_NTL = "0" %}
{% endif %}
{% if WITH_NTL == "1" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://flintlib.org/flint-{{ version }}.tar.gz
  sha256: 7b311a00503a863881eb8177dbeb84322f29399f3d7d72f3b1a4c9ba1d5794b4

build:
  number: {{ build }}
  {% if WITH_NTL == "1" %}
  string: h{{ PKG_HASH }}_ntl_{{ build }}
  {% else %}
  string: h{{ PKG_HASH }}_nontl_{{ build }}
  {% endif %}
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('libflint', max_pin='x.x') }}
  {% if WITH_NTL == "0" and (linux or osx) %}
  track_features:
    - flint_with_nontl
  {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make              # [unix]
    - ninja             # [win]
    - cmake             # [win]
  host:
    - gmp
    - pthreads-win32    # [win]
    - mpfr
  {% if WITH_NTL == "1" %}
    - ntl
  {% endif %}
  run:
    - gmp
    - pthreads-win32    # [win]
    - mpfr
  {% if WITH_NTL == "1" %}
    - ntl
  {% endif %}

test:
  commands:
    - test -f $PREFIX/include/flint/flint.h   # [unix]
    - test -f $PREFIX/lib/libflint.so         # [linux]
    - test -f $PREFIX/lib/libflint.dylib      # [osx]
    - if not exist %LIBRARY_BIN%\flint-18.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\flint.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\flint\flint.h exit 1   # [win]

about:
  home: http://flintlib.org
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Fast Library for Number Theory

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
