travis:
  secure:
    BINSTAR_TOKEN: wdd1IWwRtifcq27MRPHgJhVSqBHd+NeHzZubBdShGytmGDsJTHMJmeCnbfMsoRIZv+X22ZAKnvRUnY3aedJWKxaqIKuA5f2lSau0gEZ3TIwenJTl/3gSN72rpO8z1XTiq4uiKygunO2FnI3OpPsb6VYQBG4Yg7HirvGJUD8zWADojsByegOGO5+HKtMGrU7M+7GG1JzJfS12jjCQc8wQnbIDGdPsIZ/gz+8t5S3PBQ3FWcVK1Or0Lc1Ju+RZxsdk632JbPBI4bYmwbqriXH/2fE9IU2NnR/zavRhAZd4dj/ezTucPdjUGXFUm10j82wpgJcQtU0+31DWbD2IJzJN4heplCVp9twcweHF4HsuCqYsIpzIXVmsYIrplMQkr6Bnssp5qVdI0ROGymacWjLwqv5c4zfvjyJQKiT7TGsWQYuQ/64mAV378M4YpoPOCppyPI24N+CVp5TwmoXJw4s4pyWIhDWsbQ/pANXhEGnWjdH67jMnHJXOHzA82vW373mgaiIKHzTO5Aak0Ug0jHVYskSY+YBrUB9QZzWFIuVuAcCU5DMmwMOUw/C5kO9l9ivNaDT8HPteI76dR+MGRb9dLjqfdzw4iiGq0unYqSgk+0kYKWmsKOC3AWSH2/O3/cEfVl1hfnCLl4vICY6fsWVo8Swp3eqDW+PgZs2JZt8fS/k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
